### ISSUE TITLE
Version 0.8.0 for 2.11 not published

### ISSUE THREAD

**Issue by Timunas** [guizmaii/scala-nimbus-jose-jwt#11]
Hi,

I tried to use your library in my project based on Scala 2.11 but it seems that there is no 2.11 artifacts published for 0.8.0 version.

Is it possible to release a new version supporting 2.11?

**Comment by guizmaii** [comment]
Hi,

First, sorry for the late answer. I just saw your issue.

Now, I'll check that. I have to publish a new version with libs updates. I'll ensure that the 2.11 is correctly published !

Thanks for the report :)

Jules

**Comment by guizmaii** [comment]
Hi again @Timunas,

I just published the v0.9.0 version which is available for Scala 2.12 and 2.11.


Jules
