### ISSUE TITLE
Will this library be moved to a new home?

### ISSUE THREAD

**Issue by jamesjrg** [guizmaii/scala-nimbus-jose-jwt#91]
With bintray closing, will this library be moved to a new home? Or is it recommended to switch to a different JWT library?

Thanks!

**Comment by guizmaii** [comment]
H @jamesjrg,

Yes, it'll be moved to Maven Central. I just need to make the required work.

**Comment by guizmaii** [comment]
@jamesjrg I just release a version `1.0.2` on Maven Central 😉
